title: "Anusha Jeyaseelan"
subtitle: "Senior Content Workflow Architect | Metadata, Validation & Developer Enablement"

url: "https://anushjeya.github.io"
baseurl: "/anusha-jeyaseelan"

# Collections
collections:
  posts:
    output: false
  portfolio:
    output: true
    permalink: /:collection/:name/

show_excerpts: true

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Author info
author:
  name: "Anusha Jeyaseelan"
  avatar: "/assets/images/profile.jpg"
  bio: "Senior Content Workflow Architect • Metadata • Validation • Developer Enablement"
  location: "San Jose / Bay Area, CA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:anushajeyaseelan01@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/anushajeyaseelan/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/anushjeya/anusha-jeyaseelan"

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
